### ISSUE TITLE
Obtain inductor coil wire

### ISSUE THREAD

**Issue by AznStevy** [Duke-BME-Design/Aiguille-Medicale#12]
Determine what wire to use + get the wire. Preferably it would already exist at Chesterfield.

**Comment by AznStevy** [comment]
@sphaerobolus Are there any updates on the status of our orders?

**Comment by sphaerobolus** [comment]
The suture kit and metal detector have arrived and in your locker. The rest are still pending.

**Comment by sphaerobolus** [comment]
The magnet wire is in your locker.
