### ISSUE TITLE
Order tubing for probe

### ISSUE THREAD

**Issue by kaylawf** [Duke-BME-Design/Aiguille-Medicale#17]
Structural backing

**Comment by kaylawf** [comment]
Suggested order from McMaster Carr

**Comment by kaylawf** [comment]
https://www.mcmaster.com/standard-plastic-and-rubber-tubing

**Comment by ChanceFleeting** [comment]
Awaiting Testing for reordering.

**Comment by kaylawf** [comment]
Ordered polyethylene tubing based on 2 probe decision matrices
