### ISSUE TITLE
Put in order for cheap metal detector

### ISSUE THREAD

**Issue by AznStevy** [Duke-BME-Design/Aiguille-Medicale#3]

**Comment by ChanceFleeting** [comment]
Here's a list of cheap Wand detectors:

Tank Handheld Metal Detector Great Security For Your Business and Night Clubs 35.88
https://www.sears.com/metal-defender-handheld-metal-detector-great-security-for/p-SPM8393285302?sid=IDx20110310x00001i&gclid=EAIaIQobChMIwfTAyvDw3wIVB56fCh1o9ACcEAkYASABEgKSKPD_BwE&gclsrc=aw.ds

 Audio & Vibration Alert Handheld Security Metal Detector Wand Hand Held Scanner 33.55 
https://www.bonanza.com/listings/Audio-Vibration-Alert-Handheld-Security-Metal-Detector-Wand-Hand-Held-Scanner/632520424?goog_pla=1&gpid=68416460581&keyword=&goog_pla=1&pos=1o1&ad_type=pla&gclid=EAIaIQobChMI2MSDzfDw3wIVhZ6fCh3zgQ2nEAkYASABEgIgafD_BwE

Super Scanner Hand Held Metal Detector MD-3003B1 10.29
https://www.tvc-mall.com/details/super-scanner-hand-held-metal-detector-md-3003b1-sku84000639a.html?c=USD&utm_source=google&utm_medium=pla&utm_campaign=cse&gclid=EAIaIQobChMIy8ytwerw3wIVxF6GCh0ywgOKEAkYFCABEgLxI_D_BwE

Toy-- likely BFO but could be vlf. Large. 22.99
https://www.wickeduncle.com/gifts/boys/age-8/metal-detector---6-depth-with-led-lights?gclid=EAIaIQobChMIy8ytwerw3wIVxF6GCh0ywgOKEAkYCCABEgIXuPD_BwE
