### ISSUE TITLE
ASAIOfyi Preliminary Proposal (due 2/11)

### ISSUE THREAD

**Issue by EddieYao8** [Duke-BME-Design/Aiguille-Medicale#68]
https://docs.google.com/document/d/1jGTiidKliPW5Bidq_avap5QblmOd5svP5G0mcsFVK00/edit

**Comment by EddieYao8** [comment]
Dr. Palmeri and Richardson,

As part of the proposal, we need to outline the verification and validation plans.  Do these plans need to consider the entire FDA approval process and other bureaucratic testing regulations? 

Thanks, 

Eddie

**Comment by mlp6** [comment]
It would be good to keep the FDA requirements for this in mind when thinking this through.
