### ISSUE TITLE
Relay Driver Schematic for Circuit

### ISSUE THREAD

**Issue by EddieYao8** [Duke-BME-Design/Aiguille-Medicale#82]
with 555 and capacitor

**Comment by kaylawf** [comment]
![relay-driver](https://user-images.githubusercontent.com/36051206/52607744-4c587f00-2e45-11e9-8e47-011bdc270043.JPG)

Tried building above generic relay driver circuit; did not work properly for some reason; will try with new schematic

**Comment by ChanceFleeting** [comment]
Too slow switching time --> #96
